name: "variables"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent reruns
        run: |
          if [ $RUN_ATTEMPT_NUMBER -gt $MAXIMUM_ATTEMPTS ]; then
            echo "Exiting because the run number is greater than the maximum number of attempts"
            exit 1
          fi
        env:
          RUN_ATTEMPT_NUMBER: ${{ github.run_attempt }}
          MAXIMUM_ATTEMPTS: ${{ vars.MAXIMUM_ATTEMPTS }}
      - name: Run job
        run: |
          echo "Running job"
          sleep 1